routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::prefix('admin')->name('admin.')->group(function () {
    Route::resource('property',\App\Http\Controllers\Admin\PropertyController::class)-> except(['show']);

});

app/Models/Property.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'surface',
        'rooms',
        'bedrooms',
        'floor',
        'price',
        'city',
        'adress',
        'postal_code',
        'sold',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/PropertyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\PropertyFormRequest;
use App\Models\Property;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class PropertyController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
       return view('admin.properties.index',
           ['properties'=>Property::orderBy('created_at','desc')->paginate(25)
       ]);
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $property = new Property();
        $property -> fill([
            'surface'=> 30,
            'rooms'=> 3,
            'bedrooms'=> 1,
            'floor'=> 0,
            'city'=> 'Montpellier',
            'postal_code'=> 3400,
            'sold'=> false,
        ]);

        return view('admin.properties.form',
        [
            'property'=> $property
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(PropertyFormRequest $request)
    {
        $property = Property::create($request->validated());
        return to_route('admin.property.index')->with('success','le bien a bien été créer');
        //
    }

    /**
     * Display the specified resource.
     */

    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/admin/admin.blade.php
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <title>@yield('title')|Administration</title>
</head>
<body>

<div class="container mt-5">
    @yield('content')
</div>


</body>
</html>

<?php

resources/views/admin/properties/form.blade.php
@extends('admin.admin')

@section('title', $property->exists ? "Editer un bien" : "Créer un bien")

@section('content')

    <h1>@yield('title')</h1>

    <form class="vstack gap-2" action = "{{route($property->exists ? 'admin.property.update' : 'admin.property.store',[
    'property'=>$property ]) }}" method="post">

    @csrf
    @method($property->exists ? 'put' : 'post')

        <div class="row">
            @include('shared.input',['class'=>'col','label'=>'Titre','name'=>'title','value'=>$property->title])
            <div class="col row">
                @include('shared.input',['class'=>'col','name'=>'surface','value'=>$property->surface])
                @include('shared.input',['class'=>'col','label'=>'prix','name'=>'price','value'=>$property->price])
            </div>
        </div>
        @include('shared.input',['type'=>'textarea','name'=>'description','value'=>$property->description])
        <div class="row">
            @include('shared.input',['class'=>'col','name'=>'rooms','label'=>'pièces','value'=>$property->rooms])
            @include('shared.input',['class'=>'col','name'=>'bedrooms','label'=>'chambres','value'=>$property->bedrooms])
            @include('shared.input',['class'=>'col','name'=>'floor','label'=>'étage','value'=>$property->floor])
        </div>
        <div class="row">
            @include('shared.input',['class'=>'col','name'=>'adress','label'=>'adresse','value'=>$property->adresse])
            @include('shared.input',['class'=>'col','name'=>'city','label'=>'ville','value'=>$property->city])
            @include('shared.input',['class'=>'col','name'=>'postal_code','label'=>'code postal','value'=>$property->postal_code])
        </div>

        @include('shared.checkbox',['name'=>'sold','label'=>'Vendu','value'=>$property->sold])

        <button class="btn btn-primary" >
            @if ($property->exists)
                modifier
            @else
                créer
            @endif
        </button>

    </form>

@endsection

resources/views/admin/properties/index.blade.php
@extends('admin.admin')

@section('title','tous nos biens')

@section('content')
    <div class="d-flex justify-content-betwen align-items-center">
        <h1>@yield('title')</h1>
    </div>

    <a href="{{route('admin.property.create')}}" class="btn btn-primary">Ajouter un bien</a>

    <table class="table table-striped" >
        <thead>
        <tr>
            <th>Titre</th>
            <th>Surface</th>
            <th>Prix</th>
            <th>Ville</th>
            <th class='texte-end'>Action</th>
        </tr>
        </thead>

        <tbody>
        @foreach($properties as $property)
            <tr>
                <td>{{$property->title}}</td>
                <td>{{$property->surface}}m2</td>
                <td>{{number_format($property->price,thousands_separator: '')}}</td>
                <td>{{$property->city}}</td>
                <td>

                </td>
            </tr>

        @endforeach
        </tbody>

    </table>
    {{$properties->links()}}

@endsection

resources/views/shared/checkbox.blade.php
@php
$class ??= null ;
 @endphp
<div @class(['form-check form-switch',$class])>

    <input type="hidden" value="0" name="{{$name}}">
    <input @checked(old($name,$value ?? false))type="checkbox" value="1" name="{{$name}}" class="form-check-input @error($name) is-invalid @enderror" role="switch" id="{{$name}}">

    <label class="form-check-label" for="{{$name}}">{{$label}}</label>
    @error($name)
    <div class='invalid-feedback'>
        {{$message}}
    </div>
    @enderror
</div>

resources/views/shared/input.blade.php
@php
$type ??= 'text' ;
$class ??= null ;
$name ??= '';
$value ??= '';
$label ??= ucfirst($name) ;

@endphp

<div @class(["form-group", $class])>
    <label for="{{$name}}">{{$label}}</label>

    @if($type==='textarea')
        <textarea class="form-control @error($name) is-invalid @enderror" type="{{$type}}"
                  id="{{$name}}" name="{{$name}}">{{old($name, $value)}}</textarea>
    @else
        <input class="form-control @error($name) is-invalid @enderror" type="{{$type}}"
           id="{{$name}}" name="{{$name}}" value="{{old($name, $value)}}">

    @endif


@error($name)
    <div class='invalid-feedback'>
        {{$message}}

    </div>
    @enderror

</div>